import Head from 'next/head'
import { GetStaticProps } from 'next'
import { oauth2Client } from '@/auth/google'

type HomeProps = {
  url: string
}

export const getStaticProps: GetStaticProps<HomeProps> = async () => {
  const url = oauth2Client.generateAuthUrl({
    scope: 'https://www.googleapis.com/auth/userinfo.profile',
  })
  return {
    props: { url },
  }
}

export default function Home(props: HomeProps) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <a href={props.url}>Login with Google</a>
      </main>
    </div>
  )
}
